server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
      username: root
      password: 123456
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    banner: off
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl